# Generated by Django 4.0.3 on 2022-04-08 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='email_pessoa',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='nome_pessoa',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
