# Generated by Django 4.0.3 on 2022-04-09 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0005_alter_receita_status_receita'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita',
            name='foto_receita',
            field=models.ImageField(blank=True, upload_to='static\\img\\receitas-img'),
        ),
    ]
