# Generated by Django 4.0.3 on 2022-04-09 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0004_alter_receita_status_receita'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receita',
            name='status_receita',
            field=models.BooleanField(default=False, verbose_name='publicado'),
        ),
    ]
