# Generated by Django 4.0.3 on 2022-04-10 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0006_receita_foto_receita'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receita',
            name='foto_receita',
            field=models.ImageField(blank=True, height_field=True, upload_to='fotos\\%d\\%m\\%Y', width_field=True),
        ),
    ]
