# Generated by Django 4.0.3 on 2022-04-10 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0008_alter_receita_foto_receita'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receita',
            name='foto_receita',
            field=models.ImageField(blank=True, height_field='foto_receita', upload_to='fotos\\%d\\%m\\%Y', width_field='foto_receita'),
        ),
    ]
