# Generated by Django 4.0.3 on 2022-04-10 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0009_alter_receita_foto_receita'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita',
            name='url_height',
            field=models.PositiveIntegerField(default=300),
        ),
        migrations.AddField(
            model_name='receita',
            name='url_width',
            field=models.PositiveIntegerField(default=300),
        ),
        migrations.AlterField(
            model_name='receita',
            name='foto_receita',
            field=models.ImageField(blank=True, height_field='url_height', upload_to='fotos\\%d\\%m\\%Y', width_field='url_width'),
        ),
    ]
