# Generated by Django 4.0.3 on 2022-04-10 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0010_receita_url_height_receita_url_width_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receita',
            name='url_height',
        ),
        migrations.RemoveField(
            model_name='receita',
            name='url_width',
        ),
        migrations.AlterField(
            model_name='receita',
            name='foto_receita',
            field=models.ImageField(blank=True, upload_to='fotos\\%d\\%m\\%Y'),
        ),
    ]
